version: 0.2

env:
  variables:
    PYTHONUNBUFFERED: TRUE

phases:
  install:
      commands:
        - apt-get update -y
        - apt-get install -y libaio-dev libcunit1 libcunit1-dev libgoogle-perftools4 libibverbs-dev libiscsi-dev libnuma-dev librbd-dev librdmacm-dev libz-dev glusterfs-common
        - pip3 install scipy
  build:
    commands:
        - ./configure && make && make test && python3 t/run-fio-tests.py --skip 1007 1008 --debug
                
