#!/usr/bin/env python3
#
# sctl_characterization.py       Process the data generated by the sctl_characterization shell script
#

import os
import sys
import json
import fnmatch
import argparse

def parse_args():
    parser = argparse.ArgumentParser(description="Analyze sctl_characterization data")
    parser.add_argument("directory", help="directory containing log files")

    return parser.parse_args()

def main():
    args = parse_args()

    print("bs, zranges, em, bw, 99.99th-percentile-latency, max-latency")
    for file in sorted(os.listdir(args.directory)):
        if fnmatch.fnmatch(file, "*.sctl.json"):
            params = file.split('.')
            bs = int(params[2].replace('bs',''))
            zranges = int(params[4].replace('zranges',''))
            em = int(params[5].replace('em',''))

            filename = os.path.join(args.directory, file)
            with open(filename, "r") as fp:
                jsondata = json.load(fp)
            assert jsondata['jobs'][0]['error'] == 0
            bw = jsondata['jobs'][0]['copy']['bw']
            maxlat = jsondata['jobs'][0]['copy']['clat_ns']['max']
            pctile = jsondata['jobs'][0]['copy']['clat_ns']['percentile']['99.990000']

            print(",".join(str(x) for x in (bs, zranges, em, bw, pctile, maxlat)))

if __name__ == '__main__':
    main()
