name: 'Start QEMU VM'
description: 'Start QEMU virtual machine'

inputs:
  qemu: # QEMU binary to use
    required: false
    default: "qemu-system-x86_64"
  image: # VM image file
    required: true
  ssh_fwd_port: # forward this host port to the guest's SSH port
    required: false
    default: 2022
  options: # Custom QEMU invocation options no \n at the end!
    required: false
  ram: # how much RAM to allocate to VM
    required: false
    default: "12G"
  host_key: # If true add guest host key to known_hosts
    required: false
    default: "false"
  build_fio: # If true clone and build fio on guest
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: set ssh command
      shell: bash
      id: ssh
      run: echo "CMD=ssh root@localhost -p ${{ inputs.ssh_fwd_port }}" >> "${GITHUB_OUTPUT}"
    - name: install wait-for-it
      shell: bash
      run: sudo apt-get -qq install wait-for-it
    - name: Start VM in background
      shell: bash
      run: |
        ${{ inputs.qemu }} \
          -cpu host \
          -drive file=${{ inputs.image }},format=raw,if=virtio \
          -enable-kvm \
          -smp $(nproc) \
          -nographic \
          -m ${{ inputs.ram }} \
          -display none \
          -machine q35,accel=kvm \
          -nic user,model=virtio-net-pci,hostfwd=tcp::${{ inputs.ssh_fwd_port }}-:22 \
          ${{ inputs.options }} \
          &
    - name: Wait for VM to boot
      shell: bash
      run: wait-for-it localhost:${{ inputs.ssh_fwd_port }} -t 15
    - name: Add guest host key to known_hosts
      shell: bash
      run: |
        if echo ${{ inputs.host_key }} | grep -c "true"
        then
          ${{ steps.ssh.outputs.CMD }} -o StrictHostKeyChecking=no echo
        fi
    - name: Clone fio on guest # fake a GHA environment to use checkout-action
      shell: bash
      run: |
        if echo ${{ inputs.build_fio }} | grep -c "true"
        then
          ${{ steps.ssh.outputs.CMD }} "apt-get update && apt-get install -qq git"
          ${{ steps.ssh.outputs.CMD }} "git clone https://github.com/taiki-e/checkout-action --branch v1.3.0"
          ${{ steps.ssh.outputs.CMD }} "mkdir fio && cd fio && ../checkout-action/main.sh && git log -1"
          ${{ steps.ssh.outputs.CMD }} "cd fio && ./ci/actions-install.sh"
          ${{ steps.ssh.outputs.CMD }} "cd fio && ./ci/actions-build.sh"
        fi
